# Yarn configuration for better reliability
networkTimeout: 600000
enableNetwork: true

# Retry configuration
httpRetry: 3
httpRetryDelay: 1000

# Use npm registry as fallback
npmRegistryServer: "https://registry.npmjs.org"

